# Use the official Node.js image.
FROM node:14

# Set the working directory.
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of your application code to the working directory.
COPY . .

# Expose the port your app runs on.
EXPOSE 3000

# Start your app.
CMD ["node", "server.js"]
